# Numpy: Indexing and Masking

19 July 2017 | Python

In [1]:
import numpy as np

### Example variables

In [2]:
# create an array of 8 integers
a = 2 * np.arange(8)**2 + 1

print(a)

[ 1  3  9 19 33 51 73 99]


In [3]:
# create an array of 16 integers
b = np.arange(16)

# change shape
b.shape = (4, 4)

print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### Fancy indexing (indexing with array or list)

In [4]:
# get fourth, last, and second item from 'a'
a[[3, -1, 1]]

array([19, 99,  3])

In [5]:
# get items on fibonacci sequence from 'a'
fib = np.array([0, 1, 1, 2, 3, 5])

a[fib]

array([ 1,  3,  3,  9, 19, 51])

In [6]:
# get a 2x2 array from 'a'
a[[[[2, 7], [4, 2]]]]

array([[ 9, 99],
       [33,  9]])

### Fancy indexing and slices

In [7]:
# get third, last, and first column from 'b'
b[:, [2, -1, 0]]

array([[ 2,  3,  0],
       [ 6,  7,  4],
       [10, 11,  8],
       [14, 15, 12]])

In [8]:
# get rows on fibonacci sequence, every other column, starting from the back from 'b'
fib = np.array([0, 1, 1, 2, 3])

b[fib, ::-2]

array([[ 3,  1],
       [ 7,  5],
       [ 7,  5],
       [11,  9],
       [15, 13]])

### Diagonals

In [9]:
# get diagonal from 'b'
i = np.arange(4)

b[i, i]

array([ 0,  5, 10, 15])

In [10]:
# get diagonal of lower part from 'b'
b[i[1:], i[1:] - 1]

array([ 4,  9, 14])

In [11]:
# get diagonal of upper part from 'b'
b[i[:3], i[:3] + 1]

array([ 1,  6, 11])

### Masking

In [12]:
# create a mask with True
aMask = np.ones(4, dtype=bool)

print(aMask)

[ True  True  True  True]


In [13]:
# get diagonal from 'b' using 'aMask'
b[aMask, aMask]

array([ 0,  5, 10, 15])

In [14]:
# create another mask with mixed True and False
anotherMask = np.array([[1, 0, 1, 1], [False, True, False, False], [0, 0, 1, 0], [0, 1, 1, 1]], dtype=bool)

print(anotherMask)

[[ True False  True  True]
 [False  True False False]
 [False False  True False]
 [False  True  True  True]]


In [15]:
# apply 'anotherMask' to 'b'
b[anotherMask]

array([ 0,  2,  3,  5, 10, 13, 14, 15])

In [16]:
# create a mask using a conditional expression from 'a'
conditionalMask = (a >= 9)

# apply 'conditionalMask' to 'a'
a[conditionalMask]

array([ 9, 19, 33, 51, 73, 99])

### Masking with conditionals

In [17]:
# get all items smaller than 9 from 'a'
a[a < 9]

array([1, 3])

In [18]:
# get all items smaller than 5 or larger than 10 from 'b'
b[(b < 5) | (b > 10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15])

### Using 'where'

In [19]:
# get all items larger than 10 from 'b' using 'where'
b[np.where(b > 10)]

array([11, 12, 13, 14, 15])

In [20]:
# get all columns with a value less than 3 from 'b' 
b[:, np.where(b < 3)[1]]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

<i>Notebook by <a href="https://www.michaelsjoeberg.com">Michael Sjoeberg</a>, updated 19 July 2017.</i>