# Numpy: Arrays

16 July 2017 | Python

In [54]:
import numpy as np

### Example variables

In [55]:
a = [60, 28, 49, 81]
b = [55, 634, 704, 2020]

### Creating arrays

In [56]:
# create numpy array from list, specifying type as integer
arraySingle = np.array(a, dtype='i')

print(arraySingle)

[60 28 49 81]


In [57]:
# create numpy array from nested list
arrayMulti = np.array([a, b])

print(arrayMulti)

[[  60   28   49   81]
 [  55  634  704 2020]]


In [58]:
# create numpy array of four zeros
arrayZeros = np.zeros(4)

print(arrayZeros)

[ 0.  0.  0.  0.]


In [59]:
# create 2x3 numpy array of ones
arrayOnes = np.ones((2, 3))

print(arrayOnes)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [60]:
# create numpy array of range from 0 to 50
arrayRange = np.arange(0, 50)

print(arrayRange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Using 'linspace' and 'logspace' 

In [61]:
# create numpy array of ten numbers spaced between 0 and 10 (linearly)
arrayLin = np.linspace(0, 1, 10)

print(arrayLin)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


In [62]:
# create numpy array of ten numbers spaced between 1 and 10 (logarithmically)
arrayLog = np.logspace(0, 1, 10)

print(arrayLog)

[  1.           1.29154967   1.66810054   2.15443469   2.7825594
   3.59381366   4.64158883   5.9948425    7.74263683  10.        ]


### Slicing 

In [63]:
# second to third value in 'arraySingle'
aSlice = arraySingle[1:3]

print(aSlice)

[28 49]


In [64]:
# reverse order of value in 'arraySingle'
aSlice = arraySingle[::-1]

print(aSlice)

[81 49 28 60]


In [65]:
# multidimensional slicing (3rd and 4th columns)
aSlice = arrayMulti[0:2, 2:4]

print(aSlice)

[[  49   81]
 [ 704 2020]]


### Array operations

In [66]:
# dimensions of array
arrayMulti.ndim

2

In [67]:
# shape of array
arrayMulti.shape

(2, 4)

In [68]:
# mean value of values in array
arrayRange.mean()

24.5

In [69]:
# sum of values in array
arrayRange.sum()

1225

In [70]:
# min value in array
arrayMulti.min()

28

In [71]:
# max value in array
arrayMulti.max()

2020

### Universal functions

In [72]:
# get sine of each value in 'arrayMulti' 
np.sin(arrayMulti)

array([[-0.30481062,  0.27090579, -0.95375265, -0.62988799],
       [-0.99975517, -0.56605794,  0.27947339,  0.04406199]])

In [73]:
# get multiplcation of 'a' and 'b'
np.multiply(a, b)

array([  3300,  17752,  34496, 163620])

In [74]:
# get square root of 'b'
np.sqrt(b)

array([  7.41619849,  25.17935662,  26.53299832,  44.94441011])

In [75]:
# get minimum values from either 'a' or 'b'
np.minimum(a, b)

array([55, 28, 49, 81])

In [76]:
# get sum of axis (columns) of 'arrayMulti'
np.sum(arrayMulti, axis=1)

array([ 218, 3413])

<i>Notebook by <a href="https://www.michaelsjoeberg.com">Michael Sjoeberg</a>, updated 19 July 2017.</i>