# Numpy: Arithmetic Operations

19 July 2017 | Python

In [1]:
import numpy as np

### Example variables

In [38]:
# create an array of 6 integers
a = np.arange(6)

print(a)

# create an array of 4 integers, shaped as 2x2
b = np.arange(4)
b.shape = (2, 2)

print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]]


### Addition, subtraction, and multiplication

In [39]:
# create an array of 6 integers
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [40]:
# addition
a + a

array([ 0,  2,  4,  6,  8, 10])

In [41]:
# subtraction
a - 1

array([-1,  0,  1,  2,  3,  4])

In [42]:
# multiplication
a * 6

array([ 0,  6, 12, 18, 24, 30])

### Using 'gradient'

In [43]:
# create two arrays (same shape) of integers
x = np.array([2, 4, 5])
y = np.array([6, 2, 8])

print(x)
print(y)

[2 4 5]
[6 2 8]


In [44]:
# gradient of 'x', i.e. (4 - 2) / 1, (5 - 2) / 2, (5 - 4)/ 1
np.gradient(x)

array([ 2. ,  1.5,  1. ])

In [45]:
# gradient of 'y', i.e. (2 - 6) / 1, (8 - 6) / 2, (8 - 2)/ 1
np.gradient(y)

array([-4.,  1.,  6.])

In [46]:
# numerical derivative
np.gradient(y) / np.gradient(x)

array([-2.        ,  0.66666667,  6.        ])

### Broadcasting

In [56]:
# create a single column matrix (vector)
v = np.array([[2],[4]])

print(v)

[[2]
 [4]]


In [73]:
# scalar (multiplication)
b * v

array([[ 0,  2],
       [ 8, 12]])

In [74]:
# dot product
np.dot(b, v)

array([[ 4],
       [16]])

### Example: operations on higher dimension arrays

In [75]:
# create a 4x3 array of integers
aMatrix = np.arange(12)
aMatrix.shape = (4, 3)

print(aMatrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [76]:
# create a 1x3 array of integers
aRow = np.array([16, 17, 18])

print(aRow)

[16 17 18]


In [77]:
# addition
aMatrix + aRow

array([[16, 18, 20],
       [19, 21, 23],
       [22, 24, 26],
       [25, 27, 29]])

<i>Notebook by <a href="https://www.michaelsjoeberg.com">Michael Sjoeberg</a>, updated 19 July 2017.</i>