# Creating Arrays With Numpy

## Import 'numpy' module

In [1]:
import numpy as np

## Example variables

In [2]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

## Creating array from list

In [3]:
# create numpy array from list
firstArray = np.array(a); firstArray

array([1, 2, 3, 4])

In [4]:
# view dimensions and shape
firstArray.ndim, firstArray.shape

(1, (4,))

## Creating multidimensional arrays from lists

In [5]:
# create numpy array from nested list
secondArray = np.array([a, b]); secondArray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
# view dimensions and shape
secondArray.ndim, secondArray.shape

(2, (2, 4))

## Creating array of zeros

In [7]:
zeroArray = np.zeros(10); zeroArray 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

## Creating array from ranges

In [8]:
# range from 0 to 100
rangeArray = np.arange(0, 100); rangeArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
# 20 numbers spaced between 0 and 1
spacedArray = np.linspace(0, 1, 20); spacedArray

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])