# Indexing And Slicing With Numpy

## Import 'numpy' module

In [1]:
import numpy as np

## Slicing arrays

In [2]:
# create a numpy array with numbers
dataNumbers = np.array([23, 75, 14, 103, 46, 32, 54, 22, 15, 78]); dataNumbers

array([ 23,  75,  14, 103,  46,  32,  54,  22,  15,  78])

In [3]:
# separate 'dataNumbers' into start, middle, and end
dataStart = dataNumbers[0:3]; print('Start:', dataStart)
dataMiddle = dataNumbers[3:7]; print('Middle:', dataMiddle)
dataEnd = dataNumbers[7:10]; print('End:', dataEnd)

('Start:', array([23, 75, 14]))
('Middle:', array([103,  46,  32,  54]))
('End:', array([22, 15, 78]))


In [4]:
# change a value in 'dataStart'
dataStart[0] = 100; print('Start:', dataStart)

('Start:', array([100,  75,  14]))


In [5]:
# view changed value in 'dataNumbers'
dataNumbers

array([100,  75,  14, 103,  46,  32,  54,  22,  15,  78])

## Indexing arrays

In [6]:
# create lists with data
dataName = ['Michael', 'Susan', 'Anna', 'Alex']
dataAge = [26, 24, 28, 27]
dataScore = [880, 920, 755, 1005]
dataTeam = ['Alpha', 'Beta', 'Beta', 'Alpha']

# create a numpy array
dataStore = np.array([dataName, dataAge, dataScore, dataTeam]); dataStore

array([['Michael', 'Susan', 'Anna', 'Alex'],
       ['26', '24', '28', '27'],
       ['880', '920', '755', '1005'],
       ['Alpha', 'Beta', 'Beta', 'Alpha']], 
      dtype='|S7')

In [7]:
# view first column in 'dataStore' (i.e. all data for 'Michael')
dataStore[:,0]

array(['Michael', '26', '880', 'Alpha'], 
      dtype='|S7')

In [8]:
# view second row in 'dataStore' (i.e. ages for all)
dataStore[1,]

array(['26', '24', '28', '27'], 
      dtype='|S7')

In [9]:
# view top-right quarter in 'dataStore' (i.e. name and age of last two)
dataStore[:2,2:]

array([['Anna', 'Alex'],
       ['28', '27']], 
      dtype='|S7')

## Finding values in array

In [10]:
# create a numpy array with numbers
numberArray = np.array([45, 75, 34, 103, 66, 50, 54, 22, 45, 78]); numberArray

array([ 45,  75,  34, 103,  66,  50,  54,  22,  45,  78])

In [11]:
# find index of numbers less than or equal to 50
numberIndex = np.where(numberArray <= 50); numberIndex

(array([0, 2, 5, 7, 8]),)

In [12]:
# find numbers less than or equal to 50 using 'numberIndex'
numberFifty = numberArray[numberIndex]; numberFifty

array([45, 34, 50, 22, 45])