# Random Numbers With Numpy

## Import 'numpy' module

In [1]:
import numpy as np

## A random number from the normal distribution

In [2]:
np.random.normal()

1.6096897471033156

## Five random numbers from the normal distribution

In [3]:
np.random.normal(size=5)

array([ 0.10484781,  0.8757138 , -0.10256386,  0.03549726,  0.56806814])

## Two random numbers from the uniform distribution

In [4]:
np.random.uniform(size=2)

array([ 0.74711201,  0.72377674])

## Four random integers between 0 and 100

In [5]:
np.random.randint(low=0, high=100, size=4)

array([55, 35, 81, 23])